version: '3'

services:
  # invoice-service:
  #   build: 
  #     context: /home/josh/projects/invoice_service
  #     dockerfile: /home/josh/projects/invoice_service/Dockerfile
  #   restart: always
  #   ports:
  #     - "8080:8080"
  

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invoicing
      DSN: "host=postgres port=5432 user=postgres password=password dbname=invoicing sslmode=disable timezone=UTC connect_timeout=5"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/



